# DB 연결정보
chinook:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: dbt
      password: "{{ env_var('DBT_PWD') }}"
      dbname: analytics
      schema: dbt_lab
      threads: 4